#启动端口
server:
  port: 9001
#dubbo
dubbo:
  application:
    name: JDBS-LOCAL
  registry:
    address: 47.98.249.11:2181
    protocol: zookeeper
    check: false
    #监控中心
    monitor:
      protocol: register
  consumer:
    check: false
    timeout: 50000
    retries: 0
  protocol:
    name: dubbo
    port: 2080
#引入Log4j2文件
#logging:
#  config: classpath:log4j2.xml